### ISSUE TITLE
Markdown icons not visible in GitHub dark mode

### ISSUE THREAD

**Issue by kanishkanarch** [Jatin1o1/Jatin1o1#2]
![jatin](https://user-images.githubusercontent.com/52484751/133023550-9a51f999-e125-4d65-86d8-3f7f099ac58f.png)

**Comment by Jatin1o1** [comment]
> ![jatin](https://user-images.githubusercontent.com/52484751/133023550-9a51f999-e125-4d65-86d8-3f7f099ac58f.png)

This because icon were black colored, try replacing them with colored ones, they will be visible :)
